theme: jekyll-theme-cayman
title: Fun French!
description: Easy and fun steps to fluent French
github:
  page1: about.html
  page2: html-practice.html
  page3: grammar.html
  page4: vocabulary.html
  pagE5: practice.html
